import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html style={{width:"100%", height:"100%", overflowY:"hidden"}} lang="en">
      <body style={{width:"100%", height:"100%"}} className={inter.className}>{children}</body>
    </html>
  )
}
